<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SeleniumIDE" duration-ms="13547" started-at="2016-06-13T07:03:27Z" finished-at="2016-06-13T07:03:40Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="13547" started-at="2016-06-13T07:03:27Z" finished-at="2016-06-13T07:03:40Z">
      <class name="seleniumide.testng.TestNG2SeleniumRC">
        <test-method status="PASS" signature="setUp()[pri:0, instance:seleniumide.testng.TestNG2SeleniumRC@1a666bf]" name="setUp" is-config="true" duration-ms="10345" started-at="2016-06-13T15:03:27Z" finished-at="2016-06-13T15:03:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testSelenium2Junit_RC()[pri:0, instance:seleniumide.testng.TestNG2SeleniumRC@1a666bf]" name="testSelenium2Junit_RC" duration-ms="1110" started-at="2016-06-13T15:03:37Z" finished-at="2016-06-13T15:03:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at seleniumide.testng.TestNG2SeleniumRC.testSelenium2Junit_RC(TestNG2SeleniumRC.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSelenium2Junit_RC -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:seleniumide.testng.TestNG2SeleniumRC@1a666bf]" name="tearDown" is-config="true" duration-ms="2027" started-at="2016-06-13T15:03:38Z" finished-at="2016-06-13T15:03:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- seleniumide.testng.TestNG2SeleniumRC -->
    </test> <!-- Test -->
  </suite> <!-- SeleniumIDE -->
</testng-results>
